### ISSUE TITLE
false positive: "comma without space" in comments

### ISSUE THREAD

**Issue by haughki** [epacke/Indeni-CodeQual#3]
see attached. also, aside from finding the FP in comments, it's also flagging this, which doesn't seem right:

    # Sometimes a comma follows the year
    gsub(/,/, "", expire_year)   <-- flagging ",/" in the regex...

[false_positive_commaWithoutSpace_in_comments.ind.txt](https://github.com/epacke/indeni-enhancements/files/1831515/false_positive_commaWithoutSpace_in_comments.ind.txt)

**Comment by epacke** [comment]
I meant to submit a PR for you to review, but accidentally pushed to master. I will enable restrictions to avoid that happening again. Would you like to go through the commit and close the issue?

**Comment by haughki** [comment]
Sure, I'd like to take a look, just to learn. I'll get to it in the next few days. Thanks :)
