### ISSUE TITLE
"Failed to execute undefined" message shows up under "Exceptions thrown when parsing"

### ISSUE THREAD

**Issue by haughki** [epacke/Indeni-CodeQual#8]
To Reproduce:
run attached script in codequal:

[show-http-stats.ind.txt](https://github.com/epacke/Indeni-CodeQual/files/1921695/show-http-stats.ind.txt)

expected: Should be no exceptions under "Exceptions thrown when parsing"; or, if there are "valid" exceptions, the error message should give some more clear information about what to do about the exception. A stack trace at least...?

actual:
![image](https://user-images.githubusercontent.com/1500330/38899910-4f356c30-424e-11e8-848e-6b8264787f1e.png)

**Comment by epacke** [comment]
The script is missing the name in the comments section. Not sure if this is worth handling?

**Comment by haughki** [comment]
Just so we're clear, that's a separate issue from this bug -- one to be handled by a separate "issue" if need be. I updated the bug description above to make it more clear what I think the expected behavior should be.

In terms of the missing name in comments, I'm really surprised that command-runner didn't catch that. It seems to me like that should be a script compile error, right? If so, I think we should push that bug to indeni, and not try to flag it in codequal.

thoughts?

**Comment by epacke** [comment]
Understood. I will amend that part a bit.

**Comment by epacke** [comment]
And I agree. We should not flag it as it's not really in scope.

**Comment by epacke** [comment]
Fixed
